flowchart LR
    A[Principiante] --> B[1 Introducción]
    A --> C[2 Materiales]
    A --> D[3 Estructuras e interfaz de Excel]
    A --> E[4 Datos numéricos, fórmulas, referencias y área de impresión]
    A --> F[5 Funciones para empezar a usar Excel]
    A --> G[6 Funciones de la hoja de Excel]
    A --> H[7 Formatos que se puede aplicar en la hoja de Excel]
    A --> I[8 Insertando imágenes, iconos, formas y SmartArt]
